steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'ai-hub-assessment'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-hub-assessment:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-hub-assessment:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-hub-assessment'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-hub-assessment:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/ai-hub-assessment:$COMMIT_SHA'
